### ISSUE TITLE
What is the difference between JSTree + PHP MYSQL?

### ISSUE THREAD

**Issue by cyberfly** [vakata/phptree#1]
Hi how this package differ than JSTree with PHP MYSQL? I know JSTree will generate the tree at the front end, but what is the difference at PHP side?

Thanks

**Comment by vakata** [comment]
This repo is a collection of classes aimed at storing a tree structure in a relational database (as stated in the readme). The only connection with jstree is that both deal with trees and I am the author - nothing more.
